### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/pymlviz#67]
- Great work with the functions and tests, excellent coverage. Good test documentation.
- Redundant code, delete `pymlviz.py`.
- Functions still missing examples, except `plot_confusion_m`.
- 1 warning in `test_output_plot_number` (check if you get it, might be an issue in my computer)

**Comment by anasm-17** [comment]
The warning is in matplotlib as I disabled GUI backend for running test cases smoothly on MacOS and windows github virtual machines. The warning simply states that the GUI backend is disabled and is nothing too severe, I discussed this with tiffany and it is ok. Thanks for the feedback! :)

**Comment by yavyx** [comment]
Noted, thanks @anasm-17 !
